### ISSUE TITLE
conjure log file stops graceful quit

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#221] opened 2021-07-05 12:36 UTC
Taken from slack channel:

Hi - I am seeing log files like this “conjure-log-66961.cljc” produced in the project folder that I have not seen before. There are times where I can’t quit nvim without q! as the logfile is modified; I save and it immediately becomes modified again etc etc. 

1. This is not currently reproducible but does keep occurring with my setup.
2. It is suspected the nofile option on the log file is being changed 
3. It seems to occur when a connection is no longer open; might be related to the bb repl connection being replaced by and then closed by jvm nrepl.

**Comment by Olical** [comment] 2021-07-07 08:48
Since this one is illusive, anyone that has also seen this I would love to hear interesting things about your setup or if you can reproduce it!

For instance, do you make heavy use of session management? Do you use mappings to write all open files to disk?

Any clues will help me work out what's going on and defend against it 😄

**Comment by nbardiuk** [comment] 2021-07-07 11:42
One scenario that I often find myself:
* open log buffer with `<localleader>lv`
   check that `:set buftype` returns `nofile`
* delete the log buffer with `:bd`
* open log buffer with `<localleader>lv`
  check that `:set buftype` returns nothing

with `buftype` being cleared the log buffer becomes modified

**Comment by Olical** [comment] 2021-07-10 13:25
Hopefully fixed in `develop`! I didn't realise how weird and nuanced `:bd` was! So now I look for existing but unloaded buffers of the same name as the log buffer and I revive them by setting the appropriate options.

`:bd` was basically doing nothing other than removing options and mappings, but otherwise leaving the buffer where it was! It's more of an "unload but don't delete".

**Comment by thecontinium** [comment] 2021-07-11 08:17
Cheers. I'll run with develop and let you know.

**Comment by thecontinium** [comment] 2021-07-14 16:59
I have been running on the develop branch and have not seen this issue.

**Comment by Olical** [comment] 2021-07-18 13:39
Sweet! I'm just trying to address some Windows related issues over in #224, I'll merge and release this as soon as that's resolved. Thanks for testing!

**Comment by Olical** [comment] 2021-07-19 17:41
Should be fixed in `v4.22.0`!

**Closed by Olical** 2021-07-19 17:41 UTC
Labels: bug
