### ISSUE TITLE
HUD displayed although log buffer is opened

### ISSUE THREAD

**Issue by nimaai** [Olical/conjure#621] opened 2024-11-20 09:42 UTC
I don't know if this is expected behaviour but I would prefer that the HUD be displayed only if the log buffer is not opened.

I like to use both: HUD for small eval results and log buffer for big ones.

Thanks.

**Comment by russtoku** [comment] 2024-11-21 23:28
I don't normally use the HUD but I changed my config to allow it. I noticed that after a handful of evaluations with the log buffer opened in a horizontal split the HUD will display.

**Comment by Olical** [comment] 2024-11-22 11:34
Related to #615, there's a misconception or a bug here. Not sure which, maybe both!

The HUD appears if the log has been appended to when the bottom of it is _off screen_. So if you have the log open but you're looking at the top and something is added to the bottom, 1000 lines away, the HUD will appear to show that new content.

If you're seeing output at the bottom of the log _and_ the HUD is appearing then that behaviour is maybe not working as intended. I think some people would prefer the HUD to never appear if a log buffer is open though, so to give those people a choice, how about I make the behaviour an enum.

The default being "show HUD if new log lines aren't visible" and an alternate behaviour being "show HUD is log isn't open in this tab" - because a log in another tab shouldn't stop the HUD appearing in my opinion.

Thoughts?

**Comment by nimaai** [comment] 2024-11-22 17:05
@Olical 

perfect solution from my point of view.

**Comment by russtoku** [comment] 2024-11-22 19:34
Agreed!

**Comment by Olical** [comment] 2024-12-01 19:19
Pushed a change to `main` for this, you can set `g:conjure#log#hud#open_when` to `"log-win-not-visible"` so that the HUD only opens when the log isn't visible at all. It'll ignore the whole "can you see the last log line" feature. Hope this helps!

**Comment by Olical** [comment] 2024-12-01 19:19
Since this is an enum there should be room to add more ideas in the future if they arise.

**Comment by Olical** [comment] 2024-12-05 12:09
Nice! Closing this for now, hopefully it's acceptable for people who want to be more strict with when the HUD can open. I still like the "smart" mode but totally get people wanting a more clear line for when the HUD opens or not.

Please re-open if you have issues or ideas. Make sure you're on the latest commit of the `main` branch if the new option isn't working for you.

**Closed by Olical** 2024-12-05 12:09 UTC
Labels: bug
