### ISSUE TITLE
Error: invalid lnum 22

### ISSUE THREAD

**Issue by BerkeleyTrue** [Olical/conjure#309] opened 2022-02-08 04:56 UTC
If I open a clojure file directly I get this error
![image](https://user-images.githubusercontent.com/6775919/152920771-a4cf54de-49d6-4560-959b-8a89ccebd079.png)

And it will direct my current buffer to the conjure buffer. 

This doesn't happen if I open nvim first without a file argument, then wait a second to open a clojure file. 

Also doesn't happen in fennel files.

On commit 93a6685

![image](https://user-images.githubusercontent.com/6775919/152921051-3b08c473-65fe-4473-8c7d-3e63b902e828.png)

**Comment by Olical** [comment] 2022-02-08 10:49
I don't think I'm issuing any line related commands, so I suspect this is another plugin conflicting with things? I have no idea what `ml_get` is but that seems to be the culprit. I'll dig into this when I get a chance. Sorry for the error!

**Comment by Olical** [comment] 2022-02-12 15:04
Seems like last time this happened it was a bug inside Neovim itself 🤔  https://github.com/neovim/neovim/issues/2408

**Comment by Olical** [comment] 2022-02-12 15:05
And maybe treesitter or even CoC related https://github.com/neovim/neovim/issues/12867 hmm, not sure if there is anything I can do about it and I can't reproduce it.

**Comment by Olical** [comment] 2022-05-02 11:16
Is this still happening? Just out of interest.

**Comment by Olical** [comment] 2022-05-28 12:31
Closing for now, will open again if I can repro.

**Closed** 2022-05-28 12:31 UTC
Labels: bug, client-clojure
