### ISSUE TITLE
Is completion supported for clojurescript?

### ISSUE THREAD

**Issue by FongHou** [Olical/conjure#84] opened 2020-05-12 02:13 UTC
Hi, first want to say this is a great tool, elegent design and snappy implemenation. 

Just a quick question. Doc is not very clear whether completion is supported for clojurescript or not. Eval and everything else seems working fine in shadow-cljs session, except auto completion (I use coc-conjure, which works fine for clojure sessoin).

Thanks!

**Comment by Olical** [comment] 2020-05-12 09:28
Yep! It works fine as long as you have the CIDER middleware installed. Here's the example configuration I use for this:

```edn
{:source-paths
 ["dev/src"]

 ;; This is the key really.
 :dependencies
 [[cider/cider-nrepl "0.24.0"]]

 :dev-http {8080 "dev/public"}

 :builds
 {:app {:target :browser
        :output-dir "dev/public/js"
        :asset-path "/js"
        :modules {:main {:entries [dev.sandbox]}}}}}
```

I need to create some guides for this sort of thing on the wiki really.

**Comment by FongHou** [comment] 2020-05-12 19:13
Thanks for the answer. 

I do have cider-nrepl dependency, and can comfirm it works fine with fully qualified namespace prefix but not prefix aliaes.

**Comment by Olical** [comment] 2020-05-12 19:27
Hmm, I'll give it a check but it worked for me last time I tested it. Have you definitely required the namespace? With the require and `:as` in the namespace form?

**Comment by FongHou** [comment] 2020-05-12 20:54
Yes, I definitely did. Here is an example. 

```
(ns cljapp.data
  (:require [clojure.spec.alpha :as s]
                [clojure.string :as str]
                [spec-tools.core :as st]
                [spec-tools.data-spec :as ds]
                [applied-science.js-interop :as j]))
```
Also ran lua require 'conjure.eval'['buf']() command successfully, and conjure eval form works fine with code using alias prefix.

**Comment by FongHou** [comment] 2020-05-12 21:04
One more peice of info. I tried to verify what session-type I was in when working on cljs file, conjure display-session-type action always gave this error. Not sure this has anything to do with the completion problem.

`; conjure.client.clojure.nrepl error: ...skeller/.config/nvim/plugged/conjure/lua/conjure/log.lua:236: String cannot contain newlines`

**Comment by Olical** [comment] 2020-05-13 11:41
So this is working for me with Deoplete and the following keyword pattern for Clojure:

```
(nvim.fn.deoplete#custom#option :keyword_patterns {:clojure "[\\w!$%&*+/:<=>?@\\^_~\\-\\.#]*"})
```

Which completion tool are you using? If it's deoplete you may want to improve the default keyword pattern by using something like mine.

The session type one is weird too since it works fine for me :thinking: I'll try to reproduce it.

**Comment by Olical** [comment] 2020-05-13 11:46
Added a guard against multiline session type results even though they should NEVER exist. What I think is happening is that the session type eval is failing and it's returning an error that I'm trying to print as a single line.

This change means you will at least _see_ that error instead of having it suppressed. Then I should probably add some smarter guards that handle error states here better, but I hope it's an edge case.

**Comment by Olical** [comment] 2020-05-13 12:07
I'm improving session type detection some more, it's a lot more robust now.

And you're right, I can't get prefixed completion to work now either! I could've sworn it _did_ work (only finding this issue in CLJS too).

I'm investigating.

**Comment by Olical** [comment] 2020-05-13 12:29
Oops, I wasn't setting the session for completions, that's why it was broken! It works well now. Let me know what you think! (on `develop` but will release soon)

**Comment by Olical** [comment] 2020-05-13 12:40
![image](https://user-images.githubusercontent.com/315229/81813330-3d1c2180-951f-11ea-848e-52a50a128e26.png)

**Comment by FongHou** [comment] 2020-05-13 14:26
Works Great! Thank you for resolving this so fast! 


![image](https://user-images.githubusercontent.com/13973254/81819958-f9fd8680-94fd-11ea-8fcf-c826d14dbd9e.png)

Noticed two minor issues:

1. In above screenshot on the right, conjure eval log shows a comment "Couldn't determine session type." even though session-type is displayed correctly. 

2. (defn config-dir) in fs.fnl throw an error. 

![image](https://user-images.githubusercontent.com/13973254/81820504-b22b2f00-94fe-11ea-8b96-4ae6b3d6e942.png)

I did a quick workaround fix - swapping (or ...) conditions. it'll still throw if XGD_CONFIG_HOME is undefined in shell.

```
diff --git a/fnl/conjure/fs.fnl b/fnl/conjure/fs.fnl
index 6cdec69..171b645 100644
--- a/fnl/conjure/fs.fnl
+++ b/fnl/conjure/fs.fnl
@@ -5,9 +5,8 @@
 (defn config-dir []
   "Return $XDG_CONFIG_HOME/conjure.
   Defaulting the config directory to $HOME/config."
-  (..  (or (nvim.fn.getenv "XDG_CONFIG_HOME")
-           (.. (nvim.fn.getenv "HOME")
-               "/.config"))
+  (..  (or (.. (nvim.fn.getenv "HOME") "/.config")
+           (nvim.fn.getenv "XDG_CONFIG_HOME"))
       "/conjure"))

 (defn findfile [name path]
diff --git a/lua/conjure/fs.lua b/lua/conjure/fs.lua
index 3984a48..08fd485 100644
--- a/lua/conjure/fs.lua
+++ b/lua/conjure/fs.lua
@@ -28,7 +28,7 @@ do
   do
     local v_23_0_0 = nil
     local function config_dir0()
-      return ((nvim.fn.getenv("XDG_CONFIG_HOME") or (nvim.fn.getenv("HOME") .. "/.config")) .. "/conjure")
+      return (((nvim.fn.getenv("HOME") .. "/.config") or nvim.fn.getenv("XDG_CONFIG_HOME")) .. "/conjure")
     end
     v_23_0_0 = config_dir0
     _0_0["config-dir"] = v_23_0_0
@@ -70,4 +70,4 @@ do
   _0_0["aniseed/locals"]["resolve"] = v_23_0_
   resolve = v_23_0_
 end

```


PS. I use conjure with clojure-lsp and coc-conjure.nvim. I think they are the best combination. Conjure is awesome at repl driven flow, clojure-lsp (plus clj-kondo) are great at static analysis assisted code navigation/completion, and linting. The best part is that clojure-lsp provide these capablities before code even get eval in repl successfully, as soon as repl state gets updated conjure can provide more accurate completion context from cider-nrepl. The only tricky part is how to manage conflicts of completion sources and keymappings. Good news is I manage to integrate them well into a coc.nvim plus vim-which-key config.  coc.nvim has capability to sort completion sources by priority (ie. conjure higher than clojure-lsp), and vim-which-key provides discoverability of leader key menu (it's also a great way to discover key conflicts in the first place).

**Comment by Olical** [comment] 2020-05-13 17:24
I can't reproduce the session type error :thinking:  I saw that a while ago on an older commit, but not since. Maybe you were on a slightly older develop?

**Comment by Olical** [comment] 2020-05-13 17:25
And I'm hoping I've fixed the config issue, but we'll see. I am defaulting that XDG_CONFIG_HOME value, it's just throwing an error on _some_ systems and I wonder if it's to do with certain operating systems.

**Comment by Olical** [comment] 2020-05-13 17:25
Going to close this for now though since the core issue is fixed! :smile:

**Closed by Olical** 2020-05-13 17:25 UTC
