### ISSUE TITLE
Async/await doesn't work with ipython REPL

### ISSUE THREAD

**Issue by sheluchin** [Olical/conjure#545] opened 2023-12-13 13:49 UTC
I wanted to use the ipython REPL because it supports `await` expressions. The easiest way to switch was to start it with the `ipython --classic` flag so the prompt would be identical. Everything seemed to work okay, but `await` expressions still failed. Enabling debug mode with `let g:conjure#debug = v:true` produced this result:

```
# "ipython --classic" (started)
# --------------------------------------------------------------------------------
# eval (word): 1
# debug: send
"1
"
# debug: receive
"out" nil "1
"
# debug: receive
"out" nil ">>> "
1
# --------------------------------------------------------------------------------
# eval (root-form): async def foo(): return 'foo result'
# debug: send
"import base64
exec(base64.b64decode('YXN5bmMgZGVmIGZvbygpOgogICAgcmV0dXJuICdmb28gcmVzdWx0Jw=='))
"
# debug: receive
"out" nil ">>> "
# debug: receive
"out" nil ">>> "
# --------------------------------------------------------------------------------
# eval (root-form): result = await foo()
# debug: send
"import base64
exec(base64.b64decode('cmVzdWx0ID0gYXdhaXQgZm9vKCk='))
"
# debug: receive
"out" nil ">>> Traceback (most recent call last):
  File \"/home/foo/.pyenv/versions/3.9.5/envs/py3-9_global/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File \"<ipython-input-7-37006b858026>\", line 1, in <module>
    exec(base64.b64decode('cmVzdWx0ID0gYXdhaXQgZm9vKCk='))
  File \"<string>\", line 1
SyntaxError: 'await' outside function

>>> "
# (out) Traceback (most recent call last):
# (out)   File "/home/foo/.pyenv/versions/3.9.5/envs/py3-9_global/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
# (out)     exec(code_obj, self.user_global_ns, self.user_ns)
# (out)   File "<ipython-input-7-37006b858026>", line 1, in <module>
# (out)     exec(base64.b64decode('cmVzdWx0ID0gYXdhaXQgZm9vKCk='))
# (out)   File "<string>", line 1
SyntaxError: 'await' outside function
```

Running the same code outside of Conjure produces the correct result:
```
$ ipython --classic
Python 3.9.5 (default, Jun  3 2021, 15:11:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.
>>> async def foo():
...     return 'foo result'
...
>>> result = await foo()
>>> result
'foo result'
>>>
```

@Olical we spoke about this and you mentioned you wanted to review why you implemented it using `exec` in the first place and whether there's a way to send code right to the REPL instead. I'm just filing this issue here to help track it. Thanks for your work on Conjure!

**Comment by Olical** [comment] 2023-12-16 15:41
Testing this myself, it looks like if you don't assign the result to something then it _does_ work.

```python
async def slow_fn():
    return "slow_fn result, this is async!"


await slow_fn()
```

Yields the correct string.

**Comment by Olical** [comment] 2023-12-16 15:43
But _only_ if I evaluate `await slow_fn()` on it's own. If I eval the function and the call in a visual block it gives me the "await must be inside an async function" error.

**Comment by Olical** [comment] 2023-12-16 16:01
If we could unwrap the evals so they were not wrapped in `exec` this problem would go away. But then https://github.com/Olical/conjure/issues/437 would come back, that's a deal breaker 😢  unless for some reason #437 doesn't manifest in ipython? If so we could make the exec wrapper a toggle. But I suspect it does manifest, worth checking.

**Comment by Olical** [comment] 2023-12-16 16:03
Ah! So the reason the `await` without assignment works is because we DO NOT wrap the code in an exec wrapper if the code passes this test:

```fennel
(defn str-is-python-expr?
  [s]
  (let [parser (vim.treesitter.get_string_parser s "python")
        result (parser:parse)
        tree (a.get result 1)
        root (tree:root)]
    (and (= 1 (root:child_count))
         (is-expression? (root:child 0)))))
```

**Comment by Olical** [comment] 2023-12-16 16:21
I think we'd need some special case workarounds, like if we see `word = await .*` then we remove the wrapping, which might break other code. I think the solution I'm leaning towards right now is to just drop the `result =` and instead just `await fn()`, printing the result to the log.

If you need to capture the result in a variable then I think this is the best bet as a workaround right now:

```python
async def slow_fn():
    return "slow_fn result, this is async!"


await slow_fn()

result = None


async def capture():
    global result
    result = await slow_fn()


await capture()
result # prints the string
```

Not ideal, but it's something for now.

**Comment by sheluchin** [comment] 2023-12-16 18:27
@Olical I'm not totally clear on exactly how, but I think this might help:
```python
from IPython.terminal.embed import InteractiveShellEmbed

ipshell = InteractiveShellEmbed()

ipshell.run_cell("""
async def slow_fn():
    return "slow_fn result, this is async!"
""")
execution_result = ipshell.run_cell("await slow_fn()")
execution_result.result
```

Here's what the execution looks like in the Conjure REPL:
```
# "ipython --classic" (started)
# --------------------------------------------------------------------------------
# eval (root-form): from IPython.terminal.embed import InteractiveShellEmbed
# --------------------------------------------------------------------------------
# eval (root-form): ipshell = InteractiveShellEmbed()
# --------------------------------------------------------------------------------
# eval (root-form): ipshell.run_cell(""" async def slow_fn(): return "slow_f...
# (out) <ExecutionResult object at 7f76e2c3a110, execution_count=None error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7f76e2c398d0, raw_cell="
# (out) async def slow_fn():
    return "slow_fn result, .." store_history=False silent=False shell_futures=True cell_id=None> result=None>
# --------------------------------------------------------------------------------
# eval (root-form): execution_result = ipshell.run_cell("await slow_fn()")
Out[1]: 'slow_fn result, this is async!'
# --------------------------------------------------------------------------------
# eval (root-form): execution_result.result
'slow_fn result, this is async!'
```

**Comment by Olical** [comment] 2023-12-16 22:28
Oh that could be very useful, it would however require a completely different evaluation wrapper when in IPython 🤔 which isn't impossible, just an extra layer of complexity to worry about. Thank you for sharing this. Maybe we should have a switch or function you can call that swaps the interpreter to ipython _and_ changes how evaluated code is wrapped. Or we just copy the current client and modify it for ipython...

**Comment by russtoku** [comment] 2023-12-17 07:32
I'm inclined to suggest that a separate iPython client be forked from the Python client as there are iPython-specific tweaks that could be done. This would keep both "clean" and focused on the needs of the indiviual REPLs.

**Comment by sheluchin** [comment] 2023-12-18 15:04
I think a separate client makes sense given that IPython provides a rich set of functionality that the normal Python shell doesn't include such as the [built-in magics](https://ipython.readthedocs.io/en/stable/interactive/magics.html).

**Comment by sheluchin** [comment] 2024-01-05 15:49
@Olical async/await support might actually be a whole lot easier than we first thought :) 

https://github.com/python/cpython/pull/101243

```python
# "python -iq -m asyncio" (started)
# --------------------------------------------------------------------------------
# eval (root-form): async def slow_fn(): return "slow_fn result, this is asy...
None
# --------------------------------------------------------------------------------
# eval (word): slow_fn
<function slow_fn at 0x7f9bc78d3d90>
# --------------------------------------------------------------------------------
# eval (root-form): await slow_fn()
'slow_fn result, this is async!'
```

**Comment by russtoku** [comment] 2024-01-05 16:28
Excellent!

I can confirm that running a Python REPL with "-m asyncio" option does run the asyncio REPL for 3.10 and 3.11. And you can evaulate "await slow_fn()" from Conjure.

The referenced merged issue for Python indicates that this is possible with 3.8 and later.

**Comment by sheluchin** [comment] 2024-01-07 20:14
@russtoku thanks very much for confirming on your end.

@Olical Not sure if I should close this issue now. On the one hand, what I ultimately wanted was async/await support in conjure and we have that now using `python`, but the phrasing of this issue made it about getting ipython's native async/await support working in conjure, which we still don't have. Thank you for your time and feedback here; I'll leave it up to you to close the issue or leave it open.

**Comment by Olical** [comment] 2024-01-12 11:34
This is so cool! Thank you very much for sharing, I think it's the best approach with the least change required. The best support is native support. I think for now we can use this as the recommended approach, maybe some day we'll need to do something for ipython too, but I think this is good enough for now.

**Closed by Olical** 2024-01-12 11:34 UTC
Labels: bug, client-python
