### ISSUE TITLE
"unexpected result" from CIDER info op

### ISSUE THREAD

**Issue by campbellr** [Olical/conjure#82] opened 2020-05-08 02:16 UTC
I don't really know anything about CIDER, but it looks like Conjure isn't handling the result of cider-nrepl's `info` op when used on clojure symbols

Conjure seems to only pretty-print the result when it has a `javadoc` field, but for Clojure symbols it has a `doc` field instead:

```
; debug: send
{
  :id "37367891-e67a-4dd6-8863-0cd2250874b3"
  :ns "my.test.namespace"
  :op "info"
  :session "54d86cbf-aaac-449d-9d60-a1efc8626595"
  :symbol "s/nilable"}

; debug: receive
{
  :arglists-str "[pred]"
  :column 1
  :doc "returns a spec that accepts nil and values satisfying pred"
  :file "jar:file:/Users/ryancampbell/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar!/clojure/spec/alpha.clj"
  :id "37367891-e67a-4dd6-8863-0cd2250874b3"
  :line 1855
  :macro "true"
  :name "nilable"
  :ns "clojure.spec.alpha"
  :resource "clojure/spec/alpha.clj"
  :session "54d86cbf-aaac-449d-9d60-a1efc8626595"
  :status [ "done"]}

```

If it matters, I'm using `cider-nrepl` 0.24.0

EDIT: adding the result of `doc` for completeness:

```
; doc (word): s/nilable
; debug: send
{
  :code "(do (require 'clojure.repl)(clojure.repl/doc s/nilable))"
  :column 24
  :file "/Users/ryancampbell/test/src/my/test.clj"
  :id "1dd39eed-f366-4fdf-a4c9-34c6ef8b74cb"
  :line 42
  :nrepl.middleware.print/print "conjure.nrepl.pprint/pprint"
  :op "eval"
  :session "54d86cbf-aaac-449d-9d60-a1efc8626595"}

; debug: receive
{
  :id "1dd39eed-f366-4fdf-a4c9-34c6ef8b74cb"
  :ns "user"
  :session "54d86cbf-aaac-449d-9d60-a1efc8626595"
  :value "nil"}

; debug: receive
{
  :id "1dd39eed-f366-4fdf-a4c9-34c6ef8b74cb"
  :session "54d86cbf-aaac-449d-9d60-a1efc8626595"
  :status [ "done"]}

; No results, checking CIDER's info op

```

**Comment by campbellr** [comment] 2020-05-08 02:34
Actually looking at https://github.com/clojure-emacs/orchard/blob/master/test/orchard/info_test.clj I guess it doesn't have anything to do with my version of cider-nrepl. The format just varies a bit depending on what `info` is being called on

**Comment by Olical** [comment] 2020-05-08 09:31
Hey, thanks for the report! I'm digging into this and I can't actually reproduce it. I can doc lookup on any symbol, including `s/nilable`. Thank you so much for checking it with debug enabled!

I use both `doc` and `javadoc` depending on what's there. So at first I try to use the regular `clojure.repl/doc` macro since it's really good, if that fails and doesn't return anything I use the `info` op.

So I guess the initial `doc` lookup isn't returning anything, but then info is?

**Comment by Olical** [comment] 2020-05-08 09:38
Hmm, are you doing anything to your stdout? Like capturing it globally or something?

**Comment by Olical** [comment] 2020-05-08 09:50
My suspicion is that the initial `clojure.repl/doc` call _is_ working but my check for it wasn't working properly, then it tried `info` as a backup but it doesn't handle that result.

I've updated `develop` to have smarter handling of results from the `clojure.repl/doc` call, so hopefully that does it for you! I suspect your `doc` call is generating messages I didn't expect which threw off my check.

**Comment by campbellr** [comment] 2020-05-08 14:05
Thanks for looking into it. I dug into this a bit more too this morning, and here is what i think happened:

1. I hadn't eval-ed the buffer yet (so i was stil in the `user` namespace
2. I must have `require`-ed `my.test.namespace` at some point
3. `doc` didn't work because the the symbol `nilable` wasn't in the current namespace
4. CIDER's `info` *did* work because it was able to look up the symbol in the correct namespace.

Not sure what the right fix would be... Have `doc-str` switch to the right namespace first?

On a related note, it would be really nice conjure would also automatically `require` (in addition to `use-ns`)  correct namespace before interacting with the repl since i always forget to do `<Leader>eb`... 

That probably deserves its own issue though.

**Comment by Olical** [comment] 2020-05-11 22:04
Hmm so it does switch namespaces away from user, even if it hasn't been required yet.

It won't have the requires and aliases though if they haven't been loaded yet. I'm reluctant to add an auto-require since that could run code people _really_ don't run automatically.

I'll have a poke at this tomorrow 😄

**Comment by Olical** [comment] 2020-05-12 12:02
Hmm, I think I'll close this for now then. I _think_ it will handle weirder output from doc now, but yeah, you just need to make sure things are loaded when you're working on them. I'm reluctant to auto require right now, but I'll have a think about it and maybe add it soon. Perhaps an option? So that you can toggle it on if you know your project is safe to require all the time.

Not everyone can have auto require since the namespace might have side effects they don't want to trigger.

**Closed by Olical** 2020-05-12 12:02 UTC

**Comment by Olical** [comment] 2020-05-12 12:05
(posited the question about auto require as an option in the clojurians #conjure channel)

**Comment by campbellr** [comment] 2020-05-12 13:30
Thanks, makes sense. This was mostly user error and I get that auto require might not be something everyone wants.

> Hmm so it does switch namespaces away from user, even if it hasn't been required yet.

This is the only thing I'm unsure of. When I first looked at the code I couldn't see anywhere in the `doc-str` codepath that switched namespaces. Only `eval-str` seems to (with `in-ns`). Did I miss something or is that intentional?

**Comment by Olical** [comment] 2020-05-12 13:34
Oh damn, you're right! That's a glaring hole! I'll fix that now, thank you!

**Comment by Olical** [comment] 2020-05-12 13:38
That should help things! Thanks a lot!
