### ISSUE TITLE
Run all tests for Aniseed client does not display notification

### ISSUE THREAD

**Issue by katawful** [Olical/conjure#409] opened 2022-09-09 17:05 UTC
Buffer/module tests work normally. Changing `g:conjure#client#fennel#aniseed#aniseed_module_prefix` to my plugin's Aniseed prefix does not change anything. Conjure is installed with `develop` branch

Output from `:messages`:

```
E5108: Error executing lua ...site/pack/packer/start/aniseed/lua/aniseed/nvim/util.lua:56: ...nvim/site/pack/packer/start/aniseed/lua/aniseed/test.lua:47: module 'notify.stages.aniseed/tests' not found:
	no field package.preload['notify.stages.aniseed/tests']
	no file './notify/stages/aniseed/tests.lua'
	no file '/usr/share/luajit-2.1.0-beta3/notify/stages/aniseed/tests.lua'
	no file '/usr/local/share/lua/5.1/notify/stages/aniseed/tests.lua'
	no file '/usr/local/share/lua/5.1/notify/stages/aniseed/tests/init.lua'
	no file '/usr/share/lua/5.1/notify/stages/aniseed/tests.lua'
	no file '/usr/share/lua/5.1/notify/stages/aniseed/tests/init.lua'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/notify/stages/aniseed/tests.lua'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/notify/stages/aniseed/tests/init.lua'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/notify/stages/aniseed/tests.lua'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/notify/stages/aniseed/tests/init.lua'
	no file './notify/stages/aniseed/tests.so'
	no file '/usr/local/lib/lua/5.1/notify/stages/aniseed/tests.so'
	no file '/usr/lib/lua/5.1/notify/stages/aniseed/tests.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/notify/stages/aniseed/tests.so'
	no file './notify.so'
	no file '/usr/local/lib/lua/5.1/notify.so'
	no file '/usr/lib/lua/5.1/notify.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kat/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/notify.so'
stack traceback:
	[C]: in function 'error'
	...site/pack/packer/start/aniseed/lua/aniseed/nvim/util.lua:56: in function 'anic'
	...cker/start/conjure/lua/conjure/client/fennel/aniseed.lua:211: in function 'run-all-tests'
	[string ":lua"]:1: in main chunk
[katdotnvim.utils.export.init-test] OK 5/5 tests and 5/5 assertions passed
```

**Comment by Olical** [comment] 2022-09-25 09:37
Hmm is this through the test suite mode? Like from the CLI? Or with `<prefix>ta`? Sorry for the issue, I think "test all" has rotted, I can reproduce issues with it, but it hasn't changed really in a very long time. So my assumption is there are some modules out there that don't like to be required and inspected like I do in this test tool these days. So I need to be more careful when inspecting them to check for tests.

**Comment by katawful** [comment] 2022-09-26 02:00
I'm not sure what you mean by "test suite"/"from the CLI", but its failing on both `<localleader>ta` and `:ConjureFnlRunAllTests`

**Comment by Olical** [comment] 2022-09-26 09:34
Okay no problem! There's some command line based test running tools in Aniseed that I use to test Conjure in a headless environment, so I just wanted to check if you were using that. I'll have a look into this, definitely broken, I think it's due to some metatables on some modules at the moment.

So when testing all modules I iterate through ALL loaded modules, check if they're a table then check if they have a specific aniseed / test key if they are a table. I think they're saying they _are_ tables but when I try to inspect their keys they throw errors because of their Lua metatables. Which is fun! Your error might not be exactly that, but I've seen the issue I described and I bet it's related in some way.

On reflection, your error actually looks like one of your modules has the wrong `(module ...)` name for it's file or maybe a require is slightly wrong 🤔

**Comment by katawful** [comment] 2022-09-26 23:14
I've checked through everything in my most recently updated branch and nothing seems out of place with respect to `(module ...)` or requires

**Comment by katawful** [comment] 2022-09-26 23:26
It seems to be broken when using [nvim-notify](https://github.com/rcarriga/nvim-notify), which now makes sense with the module name found in the error

**Comment by Grazfather** [comment] 2022-10-07 14:19
It breaks on certain modules. I traced it to start of `run` in _test.fnl_

Easy repro:

```fennel
(local c (require "aniseed.core"))
(local mod (require "neogit.lib.git.cli"))
(. mod :aniseed/tests)
```

I get:

```
line    3:
E5108: Error executing lua [string ":lua"]:1: Vim(echoerr):E15: Invalid expression: ...site/pack/packer/start/neogit/lua/neogit/lib/git/cli.lua:685: unknown field
stack traceback:
        [C]: in function 'init'
        [string ":lua"]:1: in main chunk
```

So basically Olical's hunch was correct. I don't know much about meta tables but indeed that module does mess with them [here](https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/lib/git/cli.lua#L552).

**Comment by Grazfather** [comment] 2022-10-07 14:22
Actually it's probably due to [this](https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/lib/git/cli.lua#L680)

**Comment by Olical** [comment] 2022-10-08 11:19
May be fixed on develop? I made `aniseed.test` exclude any module table that has a metatable since they're unpredictable and probably not an Aniseed test module anyway. Should guard against modules that override `__index` in weird ways.

**Comment by Grazfather** [comment] 2022-10-08 11:51
I still get an error on `luasnip`. Looking into it.

**Comment by Grazfather** [comment] 2022-10-08 12:11
It looks like you map `run` BEFORE `filter`, so it fails before you have a chance to filter out the problematic modules.

**Comment by Grazfather** [comment] 2022-10-08 12:37
Looks good now!

**Comment by katawful** [comment] 2022-10-08 13:57
I'm getting the same error on the latest commit in develop still

**Comment by Grazfather** [comment] 2022-10-08 13:58
If you have your prefix changed make sure you update aniseed (on develop) as well.

**Comment by katawful** [comment] 2022-10-08 14:06
Wasn't aware that the fixes were pushed to develop. Setting `g:conjure#client#fennel#aniseed#aniseed_module_prefix` to my plugin and changing aniseed to develop in my makefile worked

**Closed** 2022-11-26 15:35 UTC
Labels: bug, client-fennel
