### ISSUE TITLE
Feature Request: Option to auto clear log

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#156] opened 2020-12-26 11:55 UTC
Add `clear_on_eval`, which can useful when the user has the log split open as he develop (I find my self navigating to the split and then to the bottom more often then not. 

Basically, this option should clear out the log buffer and replace its content on each evaluation outside the log buffer. Or, and perhaps better and more simpler in term of implementation: 

Scroll down and make the beginning of the eval comment `; eval form ...` to the top of the split such as the rest of the buffer will only contain the new evaluation.

Another option that would go hand in hand with this option above is: `disable_eval_popup_with_split`, in which it disables triggering the log popup while the log buffer or split is visible.

**Comment by Olical** [comment] 2020-12-27 10:36
Hmm not sure about this, it kinda defeats the entire point of everything being in a contextual log. The point is that you have your new thing + the context before it within easy reach, no extra steps. I tend to avoid things being removed by design, because you might need it.

I'd prefer to improve the auto scrolling if you're having issues with that? Like when you eval you could scroll to the new result immediately, kind of like a more REPL-y experience?

And as for the HUD appearing with the log visible: It's designed to open if you can't see the last line of the log buffer right now, i.e. something was appended to the log off screen so it lets you know it happened. That tolerance could probably be tweaked to make this appear far less, especially within your usecase.

It sounds like you specially use the log as a sort of REPL (something I don't really do, I edit in buffer and eval from there, the log buffer being eval-able is a rare thing for me). So maybe I can improve that UX rather than reducing the UX of other ways of using it through options.

**Comment by tami5** [comment] 2020-12-27 19:00
> Hmm not sure about this, it kinda defeats the entire point of everything being in a contextual log. The point is that you have your new thing + the context before it within easy reach, no extra steps. I tend to avoid things being removed by design, because you might need it.

I can't agree that it does defeats any point, it just a matter of preference and an option

> I'd prefer to improve the auto scrolling if you're having issues with that? Like when you eval you could scroll to the new result immediately, kind of like a more REPL-y experience?

Yep I agree, auto scrolling is the root of my issue when I open log and keep it there as I'm evaluating stuff

> And as for the HUD appearing with the log visible: It's designed to open if you can't see the last line of the log buffer right now, i.e. something was appended to the log off screen so it lets you know it happened. That tolerance could probably be tweaked to make this appear far less, especially within your usecase.

Perhaps it is something that can change? through an option that stop HUD in case of log is visible 

> It sounds like you specially use the log as a sort of REPL (something I don't really do, I edit in buffer and eval from there, the log buffer being eval-able is a rare thing for me). So maybe I can improve that UX rather than reducing the UX of other ways of using it through options.

Nothing about the feature to reduce or change anything is just two options. After your comment I think `clear_on_eval` is a bad idea if the scrolling is fixed.

**Comment by Olical** [comment] 2021-01-16 14:04
So my current thinking is that I could add an autocmd for you? Like `ConjurePreEval` since there's already `ConjureEval`. Then you can add something like this to your config and you have your auto clearing log on each eval :smile: thoughts?

```viml
autocmd User ConjurePreEval ConjureLogResetSoft
```

**Comment by tami5** [comment] 2021-01-16 14:07
Oh that's should solve it the clearing of the log. But wouldn't clear log if I'm in it and evaluate something?

**Comment by Olical** [comment] 2021-01-16 14:10
```viml
autocmd User ConjurePreEval if expand("%:t") !~ "^conjure-log-" | ConjureResetLogSoft | endif
```

Maybe that? I'm going down this angle rather than direct config because I want to make Conjure open to this sort of configuration through user code, without having to write much. This is sort of an experiment I guess to see how few hooks I need to add for you to be able to get the EXACT UX you want :slightly_smiling_face:

**Comment by tami5** [comment] 2021-01-16 15:29
@Olical  thanks so much for writing this out. Yah it is sufficient . How about disable_eval_popup in case log buffer is present?

**Comment by Olical** [comment] 2021-02-28 14:16
Going to close this issue since the core idea is sort of addressed. If there's a big need for changing how the HUD works with more config though let's do that as a separate issue.

**Closed by Olical** 2021-02-28 14:16 UTC
Labels: enhancement, question, requires-bdfl-hammock-time
