### ISSUE TITLE
Chicken Scheme eval: HUD/log buffer messy

### ISSUE THREAD

**Issue by grenle** [Olical/conjure#247] opened 2021-09-24 12:14 UTC
## Environment:

- **Ubuntu** 20.04.3 LTS
- **NVIM** v0.4.3
- **Conjure** installed with `vim-plug`  as per the `README.adoc` instructions.
- To use Chicken Scheme, add these two lines to init.vim

```
let g:conjure#client#scheme#stdio#command = "csi -quiet -:c"
let g:conjure#client#scheme#stdio#prompt_pattern = "\n-#;%d-> "
```

## Expected Behaviour

When evaluating a Chicken Scheme expression, I'm expecting comparable log/HUD/inline ouput I get evaluating MIT/GNU Scheme forms.

## Current Behaviour

The log/hud contains `^M`'s, and the expression is echoed, with the correct and expected result on the last line. Next to the evaluated expression, I get part of the echo or an empty `(out)` line.

## Problem Reproduction

In a terminal:

```bash
echo "(+ 1 9)" > tenner.scm && vim tenner.scm
```

The HUD shows up, with the correct interpreter / options:

```
; Sponsored by @valsen ❤
; --------------------------------------------------------------------------------
; csi -quiet -:c (started)
; (out)
```

Now, eval with `<localleader>ee`. The log buffer contains:

```
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 9)
; (out) (+ 1 9)^M^M
; (out) (+ 1 9)
; (out) 
; (out) 10  
```

Messy! Also, printed next to the form evaluated: `(+ 1 9) ; => (out) (+ 1 9)`

Evaluating the whole buffer or the root form doesn't help.

## With MIT/GNU Scheme 

I comment out the two Chicken Scheme specific lines in `init.vim` to switch to MIT/GNU Scheme. Evaluating `(+ 1 9)` gives a much tidier log:

```scheme
; --------------------------------------------------------------------------------
; eval (current-form): (+ 9 1)
10
```

And the result printed next to the form is what I expected: `(+ 9 1) => 10`.

## `csi` through a shell

I tried sending commands to `csi` in a regular shell. In a terminal:

```bash
(while [ 1 ]; do sleep 1; done) | csi -quiet -:c
```

And in another terminal:

```bash
$ echo "(+ 1 9)" > /proc/<CSI_PID>/fd/0
$ echo "(define miaou 'mystery-veggie)" > /proc/<CSI_PID>/fd/0
$ echo "miaou" > /proc/<CSI_PID>/fd/0
```

Going back to the terminal running `csi`, I obtain:

```scheme
#;1> #;1> (+ 1 9)
10
#;2> #;2> (define miaou 'mystery-veggie)
#;3> #;3> miaou
mystery-veggie
#;4> 
```

No echoing of expressions, and no weird carriage returns. Little messy, we are forcing console mode. The same terminal conversation without the `-:c` switch has no double-prompt. Omitting the switch in `init.vim` does not help, it still produces the same output in both the log and the line next to the evaluated form.

## Second eval example

When evaluating a more complex form, the log also includes backspaces. For example, the following:

```scheme
(define (between min max n)
  (and (>= n min)
       (<= n max)))
```

When evaluated, adds those line to the conjure log:

```
; eval (current-form): (define (between min max n) (and (>= n min) (<= n max)))
; (out) 
; (out) (define (between 
; (out) min max n
; (out) )^M^M(define ^M(define (between min max n)  (and (>= n min)^H^H^H^H^H^H^H^H^H^H^M  (and (>= n min)
; (out) 
; (out) (<= n max)^H^H^H^H^H^H^H^H^H^H
; (out) (<= n max)))
; (out) 
; (out)
```

And ` => ; (out)` is displayed next to the form.

However, the definition itself works: `(between 0 52 16)` evaluates to #t.

## ?

Am unsure of where the problem is coming from. Could someone suggest where to look next?

**Comment by Olical** [comment] 2021-09-25 11:24
Hm I can't get chicken scheme working at all right now, will try to investigate soon, some other work will have to take priority for a little while though I'm afraid.

**Comment by Olical** [comment] 2021-09-25 12:52
Hmm seems like it's actually working okay for me right now, it's not perfect but I can't see the character's you're describing... 

```scheme
; Sponsored by @daveyarwood ❤
; --------------------------------------------------------------------------------
; csi -quiet -:c (started)
; (out) 
; --------------------------------------------------------------------------------
; eval (root-form): (define (add a b) (+ a b))
; (out) 
; --------------------------------------------------------------------------------
; eval (root-form): (display "Hello, World!")
; (out) Hello, World!
; --------------------------------------------------------------------------------
; eval (root-form): (display "Hello, World!")
; (out) Hello, World!
; --------------------------------------------------------------------------------
; eval (root-form): (display "Hello, World!")
; (out) Hello, World!
; --------------------------------------------------------------------------------
; eval (root-form): (display "Hello, World!")
; (out) Hello, World!
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 2)
; (out) 3
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 2)
; (out) 3
```

I notice you're not on Neovim 0.5 yet too, which I think I'm beginning to require since it fixes a bunch of Lua -> VimL interactions that are VERY hard to work around in Neovim < 0.5 (which is now stable and has been for a few months I think).

Would you be able to try Neovim 0.5 and the Conjure `develop` branch? It's moved on quite a lot with fixes and improvements that I'm on the verge of releasing and am currently in the final testing phases.

**Comment by hi-im-buggy** [comment] 2021-09-26 08:05
The `^M` is a carriage-return character, the control character for the same. This (in addition to the `^I`s in the error log for #248, the control characters for the tab character) seems to suggest there is an underlying problem with how Conjure reads the output from the REPL, especially whitespace characters. `^H` is also the control character for backspace, though I don't understand how
that one could end up on the REPL output.

**Comment by Olical** [comment] 2021-09-26 09:34
I'm beginning to think this is a Neovim setting you have 🤔 I can't see `^I` control characters either, did you happen to set any custom Conjure config? It feels like you have some option set (in Conjure or Neovim) that's displaying characters I can't see. And I don't think it's a default setting that I have switched off otherwise I'd have a lot more reports for this I think, might be worth skimming config just to see if there's something that stands out.

Then if there _is_ an option that causes this weirdness I'll be able to repro and hopefully mitigate / fix it.

**Comment by grenle** [comment] 2021-09-26 11:42
As suggested:

- update neovim (or rather, remove neovim and install the 0.5)
- trying out the `develop` branch for Conjure

Still getting those control characters.

My `~/.config/nvim/.vimrc` contains:

```
let g:conjure#client#scheme#stdio#command = "csi -q -:c"
let g:conjure#client#scheme#stdio#prompt_pattern = "\n-#;%d-> "

call plug#begin(stdpath('data') . '/plugged')
Plug 'Olical/conjure', {'branch': 'develop'}
call plug#end()
```

I have nothing in the _legacy_ `.vimrc` .

I'm happy to re-nuke both neovim and Conjure if there is a way to ensure no options/customisation remains and try again from scratch.

**Comment by grenle** [comment] 2021-09-26 17:59
It could be my chicken. _Very crudely_ modifying `init.vim` to use Gambit:

```
let g:conjure#client#scheme#stdio#command = "/usr/local/Gambit/bin/gsi"
let g:conjure#client#scheme#stdio#prompt_pattern = "\n> "
```

I get `(out)` prefixes but simple expressions are correct and without control characters.

`csi -version` reports `Version 5.1.0 (rev 8e62f718)` which isn't the latest. Could this be the issue?

**Comment by Olical** [comment] 2021-09-27 09:37
Not sure right now but just for comparison (gotta work right now 😅), my version:

```
CHICKEN
(c) 2008-2020, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 5.2.0 (rev 317468e4)
linux-unix-gnu-x86-64 [ 64bit dload ptables ]
```

**Comment by trevarj** [comment] 2023-11-20 18:02
Hijacking to note that anyone using Chicken should also add this config:
```
vim.g["conjure#client#scheme#stdio#value_prefix_pattern"] = false
```
So that `(out)` isn't on the line of the form result
```
; eval (current-form): (+ 1 1)                                                                                                   
2
```

**Comment by paotsaq** [comment] 2024-12-03 17:51
Hello! Since this is still open, I figured I would chime in.

Chicken scheme Version 5.3.0 (rev e31bbee5)
NVIM v0.10.1

with the following on my .vimrc

```
let g:conjure#client#scheme#stdio#command = "csi -quiet -:c"
let g:conjure#client#scheme#stdio#prompt_pattern = "\n-#;%d-> "
let g:conjure#client#scheme#stdio#value_prefix_pattern = 0
```

consecutive `,ee` over `(+ 1 1)` (the only content of the file) yields:

```
; eval (current-form): (+ 1 1)
; (out) (+ 1 1)


(+ 1 1)
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 1)
; (out) (+ 1 1)


(+ 1 1)
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 1)
; (out) (+ 1 1)


(+ 1 1)
; (out) 
; (out) 2
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 1)
; (out) (+ 1 1)


(+ 1 1)
; (out) 
; (out) 2
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 1)
; (out) (+ 1
; (out) )


(+ 1 1)
; (out) 2
; --------------------------------------------------------------------------------
; eval (current-form): (+ 1 1)
; (out) (+ 1 1)


(+ 1 1)
; (out) 
; (out) 2
```

note how output is not even consistent, and there are plenty of `^M` around.

Let me know if you want to further pursue this — it would be lovely to get Chicken Scheme running properly — and how I can help, if possible! 💞

**Comment by russtoku** [comment] 2024-12-03 20:53
I can run Scheme client with MIT Scheme and Chez Scheme and get the expected behavior from Conjure.

I'm using the HEAD of Conjure's main branch.

I don't get any response with Chicken Scheme v5.4.0 on macos. Seems odd.

```
; csi (started)
; --------------------------------------------------------------------------------
; eval (current-form): (define (add a b) (+ a b))
; debug: send
"(define (add a b)
  (+ a b))
"
; --------------------------------------------------------------------------------
; eval (current-form): (display "Hello, World!")
```

**Comment by Olical** [comment] 2024-12-05 10:54
@paotsaq Ah looks like you set `let g:conjure#client#scheme#stdio#value_prefix_pattern = 0` when you need `let g:conjure#client#scheme#stdio#value_prefix_pattern = v:false` because 0 is truthy in Lua (as it should be imo!).

You can use `v:false`, `v:true` and `v:null` in Vim script if you need to pass real true, false or nil values into Lua code.

**Comment by Olical** [comment] 2024-12-05 10:55
I've added this option to https://github.com/Olical/conjure/wiki/Quick-start:-Scheme-(stdio)

**Comment by Olical** [comment] 2024-12-05 11:06
Y'know what would be really cool. If when I rewrite the stdio core that this relies on, I make it so it can "sniff" the kind of Scheme REPL you're connecting to from it's startup output then change the default config based on that. Just an idea for the future when I finally get around to giving all the stdio clients some love.

**Comment by Olical** [comment] 2024-12-05 12:06
Going to close this for now in the hopes that everyone that's in here now has the correct options set _and_ the wiki points new users in the right direction now. I'll keep "automatic scheme type detection" in the back of my mind when I am next ripping all the wiring out of that section of Conjure.

**Closed** 2024-12-05 12:07 UTC
Labels: bug, client-scheme

**Comment by paotsaq** [comment] 2024-12-05 13:09
After tinkering a bit further, I realised that my `.csirc` was somehow interfering. I don't know exactly why or how — but I set it to be blank, and now Conjure works as expected. I might chime in again if I figure out the culprit!
