### ISSUE TITLE
python repl result ends with extra '^M'  (CTRL-M)

### ISSUE THREAD

**Issue by Appalled** [Olical/conjure#439] opened 2022-11-26 12:55 UTC
Dear conjure developers, 
I run conjure on windows 10 with treesitter installed. Both fennel and python client work, while every line of python output ends with extra '^M', and there's an extra line contains 'None^M'.  I guess it's a CRLF problem. Sorry for my poor English.

![1669466905792](https://user-images.githubusercontent.com/22954918/204089871-43f5013f-6a41-4e62-a862-a63f836e3cdc.jpg)
![1669466992272](https://user-images.githubusercontent.com/22954918/204089874-b8ca1621-797c-403a-9ff4-ed31c29eee4f.jpg)

related config including:
```
Plug 'Olical/conjure'
let g:conjure#client#python#stdio#command = "python -iq"
```

system version
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2021/‎4/‎4
操作系统内部版本	19045.2251
体验	Windows Feature Experience Pack 120.2212.4180.0
```

Here are outputs of :version
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603
```

Here are outputs of  :healthcheck
```
nvim-treesitter: require("nvim-treesitter.health").check()
 
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `zig` executable found. Selected from { "zig" }
    Version: info: Usage: zig [command] [options]
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ .
  - lua            ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check

## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "python"
  - INFO: Executable: C:\Program Files\Python37\python.EXE
  - INFO: Python version: 3.7.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
 ```

**Comment by Olical** [comment] 2022-11-26 13:55
Thank you for reporting this! And there is no need to apologise for your English, it's good and I understand the issue 🙂 

I think this is because the Python REPL is printing `\r\n` whereas most REPLs on other OSs print `\n` (which Conjure splits lines on). So I think I need to split lines by `\r\n` on Windows for some REPLs.

I'll try to fix the Python client for now, to fix your problem, but maybe I'll need to fix other clients in the future.

**Comment by Olical** [comment] 2022-11-26 14:05
I've pushed a fix to the `develop` branch, I hope that works for you! I can't reproduce the issue on my machine since I don't have any development tools on my Windows PC. Please let me know if it helps. Thanks!

**Comment by Appalled** [comment] 2022-11-26 14:58
> Thank you for reporting this! And there is no need to apologise for your English, it's good and I understand the issue 🙂
> 
> I think this is because the Python REPL is printing `\r\n` whereas most REPLs on other OSs print `\n` (which Conjure splits lines on). So I think I need to split lines by `\r\n` on Windows for some REPLs.
> 
> I'll try to fix the Python client for now, to fix your problem, but maybe I'll need to fix other clients in the future.

Thanks. It works, all '^M' go away.  Both on windows and linux
there is a line contains "None" after I input \eb , is this in line with expectations?
![1669474102740](https://user-images.githubusercontent.com/22954918/204095194-9a06cfb2-3b85-4620-89a3-7b4ef4950a2b.jpg)

**Comment by Olical** [comment] 2022-11-26 15:10
That's great! And yes, `None` is expected since I think that's what `print` returns.

**Closed** 2022-11-26 15:40 UTC
Labels: bug, client-python, windows
