### ISSUE TITLE
"clojure" test runner broken in 4.17?

### ISSUE THREAD

**Issue by sigvesn** [Olical/conjure#202] opened 2021-04-07 11:47 UTC
In a CLJS project on 4.17,  running `g:conjure#client#clojure#nrepl#mapping#run_current_ns_tests`
using `g:conjure#client#clojure#nrepl#test#runner = "clojure"` results in

```run-ns-tests: rose.exp-lang-test```

being displayed, but nothing more happens. 

Reverting back to 4.16 makes the test runner work as expected.

**Comment by Olical** [comment] 2021-04-07 12:18
So it wasn't what I thought. Are you sure your test file has been evaluated / loaded before you attempted to execute the tests inside the namespace?

**Comment by Olical** [comment] 2021-04-07 12:18
I can't actually reproduce this, all testing tools are working for me in CLJ and CLJS, but maybe it's something specific about my shadow-cljs test environment.

**Comment by sigvesn** [comment] 2021-04-07 13:22
Yes, i am sure. (Even though `eval_file` and `eval_buf` does not seem to work on my test-files the first time in a new cljs repl, but that might be its own issue...)

**Comment by sigvesn** [comment] 2021-04-07 13:23
I created a minimal example project to replicate the behaviour: https://github.com/sigvesn/conjure-testrunner-fail-example

**Comment by Olical** [comment] 2021-04-07 14:42
Hmm I'll try your repro asap but that other issue you mentioned sounded really weird too, maybe they're related and something more fundamental is wrong.

It could just be figwheel + piggieback being different to shadow-cljs (which is what I used to test), I'll take a look!

**Comment by sigvesn** [comment] 2021-04-08 06:52
Thanks! The problem regarding loading of the test file is also present (for me at least)  in the repo when i open a fresh repl, start the browser and try to run the test(s).

**Comment by Olical** [comment] 2021-04-11 11:52
I think I found the issues, sadly figwheel / piggieback based cljs evaluations work a little different to normal Clojure or shadow-cljs based REPLs. If I send two forms in one eval it seems to ignore the second or maybe suppress stdout? Not sure what was going on, but I rewrote it a little to only send one form at a time and it seems happier now!

Sorry for the interruption to your service 😅 if you could check this out for yourself on the `develop` branch that'd be great! Thanks!

**Comment by sigvesn** [comment] 2021-04-12 08:26
Great, running tests now works as expected on `develop`  :)

The problem of having to load the test-file remains however, i am curious if you where able to replicate that problem as well?

**Comment by Olical** [comment] 2021-04-18 15:47
I also have to load the test file before I run the tests, that's expected, I deliberately didn't complect evaluating your code and running your tests. Just in case a user would run into issues and be surprised by it. I'd rather not ask for forgiveness in this situation.

The thing I recommend to people with this is to create their own mapping if they really need this that maybe override's Conjure's and performs an eval and then a test. If that's the issue you were describing?

**Comment by sigvesn** [comment] 2021-04-19 07:39
That makes perfect sense. The unexpected thing for me is that i cannot load the test file using the `eval_file` or `eval_buf` mappings, but have to "manually" load the file with `ConjureEval(load-file "...")`

**Comment by Olical** [comment] 2021-05-01 14:39
Closing this now since I think the core issue is fixed, if you're still having that load file issue though I may need to look into that separately. I couldn't reproduce it at the time though 🤔

**Closed by Olical** 2021-05-01 14:39 UTC
Labels: bug, client-clojure
