### ISSUE TITLE
clj-kondo linter showing up in repl buffer

### ISSUE THREAD

**Issue by esciafardini** [Olical/conjure#428] opened 2022-10-09 03:14 UTC
I recently updated all my packages and this started happening:

<img width="706" alt="Screen Shot 2022-10-08 at 11 12 02 PM" src="https://user-images.githubusercontent.com/51748017/194736052-e369597b-fbed-4a69-8abb-38584ce1b218.png">

You can see clj-kondo error indicators next to REPL output

**Comment by Olical** [comment] 2022-10-09 08:22
Duplicate of https://github.com/Olical/conjure/issues/427

And this is actually expected, it should've _always_ been like this. Neovim introduced a change which broke the HUD highlighting entirely which meant we needed to fix the original bug which was basically only HALF loading the HUD. Which meant you had highlighting but other plugins didn't kick in (like LSP, clj-kondo, etc).

So now there's a fix to properly load the buffer and trigger all autocmds but it also engages any plugins relevant for the buffer. I can not stop that from my side, in the issue linked someone put together a small autocmd they use to disable LSP in the log buffer.

Personally, I like having linting everywhere, even if there's a little visual noise sometimes.

**Comment by Olical** [comment] 2022-10-09 09:46
Added this to the FAQ https://github.com/Olical/conjure/wiki/Frequently-asked-questions#my-log-buffer-is-full-of-diagnostic-warnings-and-errors--a-plugin-is-running-in-the-log-buffer-and-i-dont-want-it-to

Because I think it will be frequently asked for a while. Closing for now, please reopen if you have further issues or need more help.

**Closed** 2022-10-09 09:47 UTC

**Comment by esciafardini** [comment] 2022-10-09 11:56
Thanks for the quick and informative response as always!
